### ISSUE TITLE
Flickr API: Re-Brand

### ISSUE THREAD

**Issue by callmeal** [boncey/Flickr4Java#1]
Need to re-brand licensing, code etc from FlickrJ. This must maintain the references required by FlickrJ's license agreement

**Comment by boncey** [comment]
Thanks for the quick response.

I don't believe that you need to do anything else.

My rough plan is to remove the existing copyright and licence notices in the code and make it clear that the BSD licence applies.
To complicate matters, this new project also has a `LICENSE-apache.txt` file in its root.
I'm not sure that means that that licence has ever applied though.
I'll just leave that file there and update the existing `LICENSE.txt` to the BSD one.
