### ISSUE TITLE
Description for Photo is being returned as NULL

### ISSUE THREAD

**Issue by tekpartner** [boncey/Flickr4Java#171]
### Subject of the issue

When I call your search method in the following manner:

PhotoList<Photo> list = flickr.getPhotosInterface().search(searchParameters, 500, 1);

The description of the photo is being returned as NULL.
### Your environment
- version of Flickr4Java - 2.16
- version of JDK - 1.8.0_77
### Steps to reproduce

Please execute the following code:

```
private Flickr flickr = new Flickr("apiKey", "sharedSecret", new REST());
String[] tags = new String[20];
tags[0] = "Cheese";
SearchParameters searchParameters = new SearchParameters();
searchParameters.setAccuracy(1);
searchParameters.setUserId("userName");
searchParameters.setTags(tags);
try {
    PhotoList<Photo> list = flickr.getPhotosInterface().search(searchParameters, 500, 1);
    Iterator itr = list.iterator();
    while (itr.hasNext()) {
        Photo photo = (Photo) itr.next();
        System.out.println(photo.getTitle(); //Getting a Valid Value
        System.out.println(photo.getDescription()); //Getting a NULL
    }
} catch (FlickrException e) {
    e.printStackTrace();
}
```
### Expected behaviour

photo.getDescription() is returning NULL
### Actual behaviour

photo.getDescription() should have returned a valid value
### Code Section that needs to be modified

PhotoUtils.java - Line 248

Current Code:

```
try {
    photo.setDescription(XMLUtilities.getChildValue(photoElement, "description"));
} catch (IndexOutOfBoundsException e) {
}
```

Proposed Code Fix:

```
try {
    photo.setDescription(XMLUtilities.getChildValue(photoElement, "description"));
    if (photo.getDescription() == null) {
        photo.setDescription(photoElement.getAttribute("description"));
    }
} catch (IndexOutOfBoundsException e) {
    photo.setDescription(photoElement.getAttribute("description"));
}
```
### Log

```
Please copy paste the log here if available

```

**Comment by boncey** [comment]
Hello, sorry it's taken me so long.
I've just taken a look at this and it seems that to get the `description` field to be returned in a search you need to provide `description` in the `extras` field.

Try something like this and see if you still get this problem please.
```
    searchParameters.setExtras(Stream.of("description").collect(Collectors.toSet()));
```
