### ISSUE TITLE
Tags are always 0

### ISSUE THREAD

**Issue by Snogo** [boncey/Flickr4Java#184]
I am having the problem that when I try to get the Tags from a photo there are always none although when I access the photo via Flickr the photo has tags. 

### Your environment
I am using Flickr4Java 2.16 and JRE 1.80_73.

### Steps to reproduce
public void addToDatastore(PhotoList<Photo> photos, long time) {
        //iterate over all of the photos in the list
        for (Photo pic : photos) {
            try {
                //make a ProcessedImage for the photo
                ProcessedImage processed = new ProcessedImage(pic, f);
                //... left out some code here
                System.out.println(pic.getUrl());
                System.out.println(pic.getDescription());
              
                //save as wel´l
                Collection<Tag> tags =  pic.getTags();
                File outputfile;
                System.out.println("Reading Tags... " + tags.size() + " Tags");
                if(tags.size()>0){
                	Tag t = Iterables.get(tags, 0);
                	System.out.println(processed.getTitle()+ "(" + t.getValue() + ")");
                    outputfile = new File(processed.getTitle() + "(" + t.getValue() + ").jpg");
                }else{
                	System.out.println(processed.getTitle());
                    outputfile = new File(processed.getTitle() + processed.getId()+ ".jpg");
                }
                
                ImageIO.write(pic.getLargeImage(), "jpg", outputfile);
             
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

I posted the method addToDatastore which should emphasize the problem. The Collection<Tag> tags is always empty (size = 0). I dont know why. Also the Description is always null.

### Expected behaviour
The tags collection should be filled with tags. When I check it on flickr itself the photos have tags and description.

### Actual behaviour
collection of the tags is empty

**Comment by boncey** [comment]
Hello, it can depend on what method you call to get the photos.

You might need to pass the word "tags" in the `extras` parameter.
You can test with and without using the [Flickr API](https://www.flickr.com/services/api/).

**Comment by Snogo** [comment]
Thanks a million. The following code works:

`Set<String> tagsWord = new HashSet<String>();
        tagsWord.add("tags");
        param.setExtras(tagsWord);`

**Comment by boncey** [comment]
Excellent.
That one catches a lot of people out.
