### ISSUE TITLE
Conflicting setter definitions for property "iconFarm" 

### ISSUE THREAD

**Issue by divlv** [boncey/Flickr4Java#186]
I'm saving the com.flickr4java.flickr.auth.Auth object to key/value storage (orchestrate.io, but, it can be any JSON-powered REST service).

Getting the object back from storage I've  got  the following exception:

` javax.ejb.EJBException: io.orchestrate.client.ClientException: com.fasterxml.jackson.databind.JsonMappingException: Conflicting setter definitions for property "iconFarm": com.flickr4java.flickr.people.User#setIconFarm(1 params) vs com.flickr4java.flickr.people.User#setIconFarm(1 params)`

Means, I can't deserialize the object from it's JSON.
What I'm doing wrong? or... is it a bug?

**Comment by divlv** [comment]
And, actually the same story for some other properties like "setIconServer", and "photosFirstDate":

`Conflicting setter definitions for property "photosFirstDate": com.flickr4java.flickr.people.User#setPhotosFirstDate(1 params) vs com.flickr4java.flickr.people.User#setPhotosFirstDate(1 params)`

**Comment by divlv** [comment]
Oh... there's even 3 variants:

>public void setPhotosFirstDate(Date photosFirstDate) {
        this.photosFirstDate = photosFirstDate;
}
>public void setPhotosFirstDate(long photosFirstDate) {
        setPhotosFirstDate(new Date(photosFirstDate));
}

>public void setPhotosFirstDate(String photosFirstDate) {
        if (photosFirstDate != null) {
            setPhotosFirstDate(Long.parseLong(photosFirstDate) * 1000);
        }
}

Why it was done so? We can't predict the type of argument, really?

**Comment by boncey** [comment]
Hello, thanks for raising this report and doing some investigating.

I inherited this project so I didn't write this code. :-)

It looks like those overloaded methods are not used though.
You could try removing the non-string variants and seeing if that fixes the problem.

**Comment by divlv** [comment]
Actually I did a workaround, simply cutting off the problematic parts.
"Auth" object was transformed to FlickrAuth:

```
public class FlickrAuth implements Serializable {

    private static final long serialVersionUID = 7252701150729211301L;

    private String token;

    private String tokenSecret;

    private FlickrPermission permission;

    public FlickrAuth() {
    }

    public FlickrAuth(String token, String tokenSecret, FlickrPermission permission) {
        this.token = token;
        this.tokenSecret = tokenSecret;
        this.permission = permission;
    }

    public FlickrAuth(FlickrPermission permission) {
        this.permission = permission;
    }

    public String getToken() {
        return token;
    }

    public void setToken(String token) {
        this.token = token;
    }

    public String getTokenSecret() {
        return tokenSecret;
    }

    public void setTokenSecret(String tokenSecret) {
        this.tokenSecret = tokenSecret;
    }

    public FlickrPermission getPermission() {
        return permission;
    }

    public void setPermission(FlickrPermission permission) {
        this.permission = permission;
    }
}

```

Because I need only token/tokenSecret for authentication.
Then, I have copied "Permission" object to FlickrPermission (I need a public constructor here)


```
	public FlickrPermission(int type) {
		this.type = type;
	}

```
And now I'm saving/serializing to the database FlickrAuth and FlickrPermission objects.
Working fine.

That's it.

**Comment by boncey** [comment]
Thanks, I'll clean up those methods next time I do a release.
