### ISSUE TITLE
Setting hasGeo(true) still return photos with no geo data

### ISSUE THREAD

**Issue by jvence** [boncey/Flickr4Java#189]
Requesting photo using hasGeo(true) still returning photo that have no geo data (geoData is null)

### Your environment
Flick4j v2.16

Simply set searchParameters.setHasGeo(true); and call  f.getPhotosInterface().search(searchParameters, 0, 0); It returns images but none have any geo data.

**Comment by boncey** [comment]
Can you give me some photo ids of ones that do contain geo data that are coming back as null please?
Then I can see what the code is doing with it.

Thanks.

**Comment by jvence** [comment]
Well I've requested a search with .setHasGeo(true) and it's returning hundred of images but without any geo data. 

Here are some ids: 
29924668232 (https://flickr.com/photos/62516562@N00/29924668232) 
29944714881 (https://flickr.com/photos/86006564@N00/29944714881)

**Comment by boncey** [comment]
OK, have you specified `geo` in the `extras` parameter?

Geo stuff doesn't come back by default, you need to tell it to return it.
This is a limitation of the Flickr API, you can read more [in the docs](https://www.flickr.com/services/api/flickr.photos.search.html).

**Comment by jvence** [comment]
Thanks. That worked. I thought that hasGeo was the same as geo in extras. Thanks for responding and for the great API!

**Comment by dimitriskkkk** [comment]
Could you please tell me what i should do to return back photos with geo data?

**Comment by dimitriskkkk** [comment]
Hi thanks for answering! I managed to do this by doing this:
` Set<String> set = new HashSet<String>();
  set.add("geo");
  searchParameters.setHasGeo(true);
`
so now i can get back the place id of every photo return fromthe api using  .getPLaceId() method.
Do you know any fast way to return the Real Name of the location and not the Id?
