### ISSUE TITLE
Android App crashes when pulling geolocation photos.

### ISSUE THREAD

**Issue by bryancresswell** [boncey/Flickr4Java#192]
### Subject of the issue
App crashes whenever I pull
### Your environment
2.16 version of Flickr4Java
8 version of JDK

### Steps to reproduce
Tell us how to reproduce this issue.
Please provide working code.
`pl = f.getPhotosInterface().getGeoInterface().photosForLocation(geoData, Extras.MIN_EXTRAS, 2, 0);`
### Expected behaviour
To pull the images based on location

### Actual behaviour
App crashes

### Log
```
Please copy paste the log here if available

```

**Comment by bryancresswell** [comment]
com.flickr4java.flickr.FlickrException: 99: Insufficient permissions. Method requires read privileges; none granted. new error

**Comment by boncey** [comment]
Hello, do you have a stack trace or an exception message please?

**Comment by bryancresswell** [comment]
Hey boncey, no worries. I've fixed the issue. I came across an issue while working with your API. Is it alright if I send you a pull request? It's with regards to one of your methods. A small change.

**Comment by boncey** [comment]
Absolutely, thanks.

I can't devote a lot of time to this project but all pull requests are gratefully received.

**Comment by bryancresswell** [comment]
Sure thing!
