### ISSUE TITLE
CA Certificates cause problems with Flickr4Java apps

### ISSUE THREAD

**Issue by Linus12** [boncey/Flickr4Java#196]
### Subject of the issue
Not caused by a problem specific within Flickr4Java, but Yahoo changed/updated some of the SSL CA Certificates recently. This manifest itself with my Flickr4Java apps crashing with the following errors:
(Stack traces removed for brevity)
````
    Exception in thread "main" org.scribe.exceptions.OAuthConnectionException: There was a problem while creating a connection to the remote service.
    Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
    Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
    Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
````

### Your environment
* Flickr4Java        - 2.15
* Java SDK          - jdk1.8.0_31
* Java Run Time  - jre1.8.0_111 

### Solution:
Found a Java source file that checks for certificate problems and tried connecting to api.flickr.com
( Source located at: [](http://nodsw.com/blog/leeland/2006/12/06-no-more-unable-find-valid-certification-path-requested-target ))

It indicated the following two certificates were missing on my system.
````
1 Subject CN=*.yahoo.com, O=Yahoo! Inc., L=Sunnyvale, ST=CA, C=US
Issuer CN=DigiCert SHA2 High Assurance Server CA, OU=www.digicert.com, O=DigiCert Inc, C=US
sha1 e9 89 e9 5d fa 31 5b a8 18 4f 59 be bb e6 fa b5 48 3e 6c e4
md5 c5 9b a5 94 6a b2 7e 68 49 13 d0 b3 6d 4e 6e b1

2 Subject CN=DigiCert SHA2 High Assurance Server CA, OU=www.digicert.com, O=DigiCert Inc, C=US
Issuer CN=DigiCert High Assurance EV Root CA, OU=www.digicert.com, O=DigiCert Inc, C=US
sha1 a0 31 c4 67 82 e6 e6 c6 62 c2 c8 7c 76 da 9a a6 2c ca bd 8e
md5 aa ee 5c f8 b0 d8 59 6d 2e 0c be 67 42 1c f7 db
````
I was able to download both the **DigiCert SHA2 High Assurance Server CA** and **DigiCert High Assurance EV Root CA** from the DigiCert web site at:
[www.digicert.com/digicert-root-certificates.htm](url)

I added them both to the cacerts file for the **jdk** but only needed to add the second one to the **jre**.

This fixed my running programs, but it seems the test program still says it is "missing" the certificates. But that may be just a problem with the specific test program as it gives the same error for www.flikr.com, yet I have no issues with those.....

Just wanted to give you a heads up in case any of the other users see this problem.

**Comment by boncey** [comment]
Thanks for letting us know.
I've not seen this problem yet with my app that uses Flickr4Java.
