### ISSUE TITLE
Oauth-How to resolve Failed to find Access token

### ISSUE THREAD

**Issue by prarthana75** [boncey/Flickr4Java#208]
### Subject of the issue
if mutiple user/request try to fetch oauth token at same time I'm getting error "Failed to find access token for token.."  Please help how to resolve this.
I've used jdbctokenstore in my appconext-security.xml , 
    <bean id="tokenStore" class="org.springframework.security.oauth2.provider.token.store.JdbcTokenStore">
      <constructor-arg ref="primaryDataSource" />
    </bean>

    
    <bean id="tokenServices" class="org.springframework.security.oauth2.provider.token.DefaultTokenServices">
      <property name="tokenStore" ref="tokenStore" />
      <property name="supportRefreshToken" value="true" />
      <property name="accessTokenValiditySeconds" value="300" />
      <property name="clientDetailsService" ref="clientDetails" />
    </bean>

    
    <bean id="userApprovalHandler" class="org.springframework.security.oauth2.provider.approval.TokenStoreUserApprovalHandler">
      <property name="requestFactory" ref="oAuth2RequestFactory" />
      <property name="tokenStore" ref="tokenStore" />
    </bean>

    <oauth:authorization-server
        client-details-service-ref="clientDetails" token-services-ref="tokenServices"
        user-approval-handler-ref="userApprovalHandler">
        <oauth:authorization-code />
        <oauth:implicit />
        <oauth:refresh-token />
        <oauth:client-credentials />
        <oauth:password authentication-manager-ref="authenticationManager" />
    </oauth:authorization-server>

```

**Comment by boncey** [comment]
Hi, can you explain how this relates to F4J please?

**Comment by boncey** [comment]
Closing due to lack of response.
Will re-open if/when the F4J link is clarified.
