### ISSUE TITLE
computing the hesse matrix with multidimensional input in tensorflow 

### ISSUE THREAD

**Issue by MiYi93** [boncey/Flickr4Java#228]
Hey there I'm new in this community. I started to program with tensorflow and I tried to compute the Hesse matrix of the prediction `y` and weights matrix `w` from a  feedforward neural network. My problem is that I can't shape the weights matrix because of the gradients function. I'm getting always:

> TypeError: Fetch argument None has invalid type <class 'NoneType'>.

Without shaping I can't compute the Hesse matrix of `y`,`w`.

Has someone an idea how to solve this problem.

    def neural_network_model(data,layer,nodes,dim,nclasses):
    
    hidden_layer = []
    for i in range(layer):
        if(i == 0):
            hidden_layer.append({'weights':tf.Variable(tf.random_normal([dim, nodes[i]])),
                              'biases':tf.Variable(tf.random_normal([nodes[i]]))})
        else:
            hidden_layer.append({'weights':tf.Variable(tf.random_normal([nodes[i-1], nodes[i]])),
                              'biases':tf.Variable(tf.random_normal([nodes[i]]))})

    output_layer = {'weights':tf.Variable(tf.random_normal([nodes[layer-1], nclasses])),
                    'biases':tf.Variable(tf.random_normal([nclasses])),}
    
    l = []
    for i in range(layer):
        if(i == 0):
            l.append(tf.add(tf.matmul(data,hidden_layer[i]['weights']), hidden_layer[i]['biases']))
            l[i] = tf.nn.relu(l[i],'sigmoid')
        else:
            l.append(tf.add(tf.matmul(l[i-1],hidden_layer[i]['weights']), hidden_layer[i]['biases']))
            l[i] = tf.nn.relu(l[i],'sigmoid')

    output = tf.matmul(l[layer-1],output_layer['weights']) + output_layer['biases']
    
    
    weights = []
    for i in range(layer): 
        weights.append(tf.reshape(hidden_layer[i]['weights'],[-1]))
    weights.append(tf.reshape(output_layer['weights'],[-1]))

    def train_neural_network(data,layer,nodes,dim,nclasses,n,n2):
        gr = []
        prediction,weights2= neural_network_model(data,layer,nodes,dim,nclasses) 
        cost = tf.square(prediction-y)
        optimizer = tf.train.AdamOptimizer().minimize(cost)
    
        gradient = tf.gradients(prediction,weights2)
        hes = tf.hessians(prediction,weights2[0])
        train = func(n,n2)
        hm_epochs = 10

**Comment by farnulfo** [comment]
Before answering your issue can you explain why you ask this here ? 
How did you find this page ?
