### ISSUE TITLE
Template for downloads of videos

### ISSUE THREAD

**Issue by jgsuess** [boncey/Flickr4Java#278]
### Subject of the issue
I am trying to obtain original-size video URLs. I have a pro account, and can successfully download original Photo urls.
Please note that this could also be an API issue:
https://github.com/jjxtra/FlickrDownloader/blob/master/FlickrDownloaderApp.cs#L267

### Your environment
* version of Flickr4Java: latest
* version of JDK: 1.8

### Steps to reproduce
1. Create a search `PhotosInterface.search()`.
2. Set the `media` to `videos`
3. API accepts the search.
4. Leaf through the response pages.
5a. Inspect the photo information for the photos retrieved for media. **OR**
5b. Blindly request `photo.getVideoOriginalUrl()`

### Expected behaviour

5a. Media type is `video`.
5b. Url points to original video download source

### Actual behaviour
5a. Media type is `photo`
5b. Url string is empty.

### Log
```
Please copy paste the log here if available

```

**Comment by jgsuess** [comment]
Update: It is a bug. Got it to work using:
```
				return "www.flickr.com/video_download.gne?id=" + photo.getId() + "&" + "originalSecret="
						+ photo.getOriginalSecret() + "&" + "secret=" + photo.getSecret();
```

**Comment by boncey** [comment]
Yes, it does seem to be a bug.

I looked at the [get sizes](https://www.flickr.com/services/api/flickr.photos.getSizes.html) method for one of my videos and it does return some information but not the actual URL.

Also, for that to be returned in a search you'd need to specify URL type to return in the `extras` field and I don't know what field name to request - it's not documented.
I'll look at adding a workaround like the code you linked to above.

**Comment by boncey** [comment]
```
return "www.flickr.com/video_download.gne?id=" + photo.getId() + "&" + "originalSecret="+ photo.getOriginalSecret() + "&" + "secret=" + photo.getSecret();
```

Did that work for you?
For one of my photos it downloaded a 720p `.mp4` file but I had uploaded a `.mov` file.

**Comment by jgsuess** [comment]
Hmmm... Could be that I got a canonised version as well. Have not actually
tested against the manual download. Feels that the whole video thing is a
bit brittle. But amazing that something so simple as downloading the
original of a video is hard with the API.

**Comment by boncey** [comment]
I've just released a new version that fixes this issue by returning the constructed URL if the API returns a blank string.
