### ISSUE TITLE
Response parsing doesn't handle HTML5 acceptable elements

### ISSUE THREAD

**Issue by ndtreviv** [boncey/Flickr4Java#302]
### Subject of the issue
Response parsing doesn't handle HTML5 acceptable elements (such as `<hr>` without trailing slash).

### Your environment
Version: 3.0.0
JDK: 8

### Steps to reproduce
```
...
        Flickr flickr = new Flickr(FLICKR_API_KEY, FLICKR_SHARED_SECRET, new REST());
        long searchSpan = (5 * 60 * 1000L);
        final Set<String> extras = new HashSet<>(Arrays.asList("url_o, tags"));
...
        // fetchDate is : 2008-12-13T21:00:01
        // page is 2
        final SearchParameters params = new SearchParameters();
        params.setExtras(extras);
        params.setMaxUploadDate(new Date(fetchDate));
        params.setMinUploadDate(new Date(fetchDate - searchSpan));
        params.setPrivacyFilter(1); // only get public photos

        try {
            final PhotoList<Photo> results = flickr.getPhotosInterface().search(params, pageSize, page);
            final String fetchDateAsString = dateFormat.format(new Date(fetchDate));
            return results;
        }
```

### Expected behaviour
In HTML5 void elements no longer need the trailing `/`

### Actual behaviour
FlickrRuntimeException parsing the response data from flickr (see logs below).

### Log
```
[ERROR] [Fatal Error] :6:3: The element type "hr" must be terminated by the matching end-tag "</hr>".
[ERROR] Error on the Flickr API for date 2008-12-13T21:00:01 and page 2
com.flickr4java.flickr.FlickrRuntimeException: org.xml.sax.SAXParseException; lineNumber: 6; columnNumber: 3; The element type "hr" must be terminated by the matching end-tag "</hr>".
	at com.flickr4java.flickr.REST.get(REST.java:161)
```

**Comment by boncey** [comment]
Flickr4Java doesn't do any parsing of HTML.
It only handles XML through the API.
What is happening I suspect is that Flickr is returning a HTML response when it should be XML - I think this happens when it's overloaded.

Does this happen consistently or just now and again?

I'd like to be able to detect it and throw a specific exception if possible.

**Comment by ndtreviv** [comment]
Just now and again. Sounds about right. Urgh. What's wrong with a 429?!
Thanks for checking it out.

**Comment by boncey** [comment]
[Release 3.01](https://github.com/boncey/Flickr4Java/releases/tag/flickr4java-3.0.1) fixes this.
