### ISSUE TITLE
SLF4J throws error due to missing .jar on classpath

### ISSUE THREAD

**Issue by Linus12** [boncey/Flickr4Java#304]
### Subject of the issue
slf4j gives the following warnings:
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

### Your environment
* version of Flickr4Java   3.0.1
* version of JDK             1.8
* version of slf4j             1.7.9

### Steps to reproduce
Replaced Flickr4Java 2.17 with Flickr 3.0.1; replaced scribe 1.3.5 with scribejava-core 6.3.0 and added slf4j 1.7.9; replaced 

### Expected behavior
OK, obviously I just need to add one of the appropriate slf4j.jar files to the class path... But would like to see documentation as to the best one to use for solving issues; at least at first, even if the recommendation is to use the -nop jar. 
Current options given on slf4j website are: slf4j-nop.jar slf4j-simple.jar, slf4j-log4j12.jar, slf4j-jdk14.jar or logback-classic.jar

**Comment by Linus12** [comment]
The issue seems to be that I used slf4j-api-1.7.9.jar  rather than one of the others. That's my bad. But the Readme just says "slf4j (runtime dependency for logging)" is required... A little help in deciding which of the 5 slf4j to use would be helpful to some of us using this for the first time.

**Comment by boncey** [comment]
This is now fixed and released as 3.0.2.
Be aware that it may take several hours to appear in Maven Central.
