### ISSUE TITLE
###form output as json in react-form-builder 2

### ISSUE THREAD

**Issue by hessaam** [boncey/Flickr4Java#323]
### form output as json in react-form-builder
I'v been trying get json output from the form that built by react form builder 2 package but I haven't been success yet.

### Your environment
* react
* React Form Builder 2

@Kiho

**Comment by Kiho** [comment]
You can get json data from here https://github.com/Kiho/react-form-builder/blob/master/examples/custom/demobar.js#L51
with `onSubmit={this._onSubmit}` in ReactFormGenerator

**Comment by hessaam** [comment]
I want creat a form whit react form builder 2 then when I click the Preview form button, the form that I created logged in console as json.
    On Tuesday, June 11, 2019, 10:47:48 AM GMT+4:30, Kiho Chang <notifications@github.com> wrote:  
 
 
You can get json data from here https://github.com/Kiho/react-form-builder/blob/master/examples/custom/demobar.js#L51
with onSubmit={this._onSubmit} in ReactFormGenerator
