### ISSUE TITLE
flickr switched urls for downloading photos

### ISSUE THREAD

**Issue by sellersj** [boncey/Flickr4Java#333]
### Subject of the issue
Library builds up url like https://farm5.static.flickr.com but flickr using https://live.staticflickr.com

### Your environment
* version of Flickr4Java 3.0.1
* version of JDK 11

### Steps to reproduce
Call PhotosInterface#getImageAsStream(Photo photo, int size) and it will build a url in Photo#_getBaseImageUrl() which uses the farm, but those don't seem to work anymore.

Not sure if it code should be changed to hardcode live.staticflickr.com or if it will need to be restructured to get the url after calling the size api first.

### Expected behaviour
It to download the file.

### Actual behaviour
Flickr generates a 410 file not found error

### Log
```
Please copy paste the log here if available

```

**Comment by boncey** [comment]
Hi @sellersj thanks for raising this.
Will try to get a fix out this weekend.

**Comment by boncey** [comment]
This is now fixed and released as 3.0.2.
Be aware that it may take several hours to appear in Maven Central.
