### ISSUE TITLE
RESTler with authentication

### ISSUE THREAD

**Issue by sharmig571** [boncey/Flickr4Java#427]
### Subject of the issue
Describe your issue here.

### Your environment
* version of Flickr4Java
* version of JDK

### Steps to reproduce
Tell us how to reproduce this issue.
Please provide working code.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Log
```
Can someone please give a working example

```

**Comment by boncey** [comment]
Hi, you can see an auth example here: https://github.com/boncey/Flickr4Java/blob/master/src/examples/java/AuthExample.java
