### ISSUE TITLE
How to get a link of "original" Image?

### ISSUE THREAD

**Issue by StepanMe** [boncey/Flickr4Java#441]
How can I get a link to the exact type size of an Image, for example "Original"?
I do this:
`
...
photoUrls = (SizeList<Size>) photosInterface.getSizes(photoId);
...`
then this:
`...
url = photoUrls.get(7).getSource();
...`
The **7th** is sometimes "small", sometimes "medium" and sometimes of other sizes

**Comment by boncey** [comment]
Hello @StepanMe.
I'm trying to figure out how the code works and it's pretty confusing.
I don't think it's very robust and might be failing as Flickr has introduced some new sizes (`X-Large 4K` for example).

Do you have some example photo ids that give different results please so I can try to work out what's going on.

**Comment by boncey** [comment]
Hi, I've added a `getLabelName()` method to Size now.
You should be able to do something like this to get the Original photo.

```
Optional<Size> original = sizes.stream().filter(size -> size.getLabelName().equals("Original")).findFirst();
```
