### ISSUE TITLE
Code cells not rendering on Jupyter lab

### ISSUE THREAD

**Issue by NgocDo22** [boncey/Flickr4Java#509]
Hi! When I launch Jupyter notebooks on Jupiter lab, code cells sometimes don't render.

For example, I tried to work with [this notebook](https://github.com/davedgd/python-bootcamp/blob/master/Unit%203/Python-Bootcamp-Unit3.ipynb) 

When I open it on Github, all the cells display properly like this:

![image](https://user-images.githubusercontent.com/74156238/131717955-8f05fea6-3120-4be9-b8b0-853fb6ff0b95.png)

But in Jupyter lab, the cells under "Comparison Operator" section, for example, just won't render:

![image](https://user-images.githubusercontent.com/74156238/131718219-fb87b1e1-91ca-4f23-b5e3-b29491f511ff.png)

Please advise if anyone has a solution here. Thanks!

@davedgd FYI!

**Comment by davedgd** [comment]
@NgocDo22: thanks for including me on this and writing a detailed issue! Did you intend to post it to the [JupyterLab repo](https://github.com/jupyterlab/jupyterlab) however? If so, I’d close this issue and move it over there instead.

**Comment by boncey** [comment]
Yes, a Python issue definitely doesn't have anything to do with this Java project. :-)
Is there any reason why you raised the issue here please @NgocDo22 ?

**Comment by NgocDo22** [comment]
Thanks @davedgd and @boncey. I'll move this issue to the related repo. Sorry for this inconvenience. My first time posting something on Github :)

**Comment by boncey** [comment]
First time is good 👍 
I was just curious why you chose this repo in particular.

**Comment by NgocDo22** [comment]
> First time is good 👍
> I was just curious why you chose this repo in particular.

I searched for how to post a question on Github and followed the link in an answer I found. I should have read more carefully that the topic discussed there was Java-related.
