### ISSUE TITLE
Original video URL returns 404

### ISSUE THREAD

**Issue by temesoft** [boncey/Flickr4Java#588]
### Original video URL returns 404
I am trying to search and download my videos with the code using flickr4java and seem to be unable to download original videos. I get links that look like this:

**https://www.flickr.com/video_download.gne?id={PHOTO_ID_HERE}&originalSecret=&secret={SOME_SECRET_HERE}**

Notice that the URL has values for "id" and "secret", but not for "originalSecret".
When navigating to that url i get back 404

### Your environment
* version of Flickr4Java: 3.0.6
* version of JDK: zulu-11-jdk

### Steps to reproduce
```
            SearchParameters searchParameters = new SearchParameters();
            searchParameters.setMedia("videos");
            searchParameters.setUserId(user.getId());
            int page = 0;
            PhotoList<Photo> videos = photosInterface.search(searchParameters, 20, page);
            while (!videos.isEmpty()) {
                for (Photo video : videos) {
                      // at this point i get the video.getVideoOriginalUrl() and try to download it but receive a 404
                      processVideo(video);
                }
             }
```

### Expected behaviour
I expected either a download or a redirect to download should happen.

### Actual behaviour
404 is returned

**Comment by boncey** [comment]
Hello, I tried your sample and it appeared to work for my videos.
I also get a link in the format you described but it works correctly when I click it.
I think this may be a problem with the Flickr API and not with Flickr4Java.

I'll close this issue but feel free to add more info (eg, your user id and the video link if it's public) so I can try to figure out why mine works and yours doesn't.

Thanks.
