### ISSUE TITLE
100: Invalid API Key (Key has invalid format)

### ISSUE THREAD

**Issue by kaciula** [boncey/Flickr4Java#93]
I am suddenly seeing this issue in my code.

Exception in thread "main" com.flickr4java.flickr.FlickrException: 100: Invalid API Key (Key has invalid format)
    at com.flickr4java.flickr.photos.PhotosInterface.search(PhotosInterface.java:1049)

The code used to work before and I haven't modified anything. Maybe it has something to do with the fact that Flicker moved to https? I've tried creating new flickr api keys but I still keep getting this exception. Any idea on what might be the problem?

**Comment by jgsuess** [comment]
I am seeing the same behaviour with the sample code block of the distro.
`Flickr f = new Flickr(apiKey, sharedSecret, new REST());
TestInterface testInterface = f.getTestInterface();
Collection results = testInterface.echo(Collections.EMPTY_MAP);`

**Comment by boncey** [comment]
@jgsuess Hi, how did you generate your key please?

**Comment by jgsuess** [comment]
I have obtained an API key and the corresponding secret from the flickr API site. I use these as first and second parameter. Do I need to go through an authorisation first? If so, could you let me know what the steps are? The example does not point to that.

**Comment by boncey** [comment]
I've just tried that code with the key and secret from one of my apps and it works fine.

Have you created an app or are you using the key & secret from the [API Explorer](https://www.flickr.com/services/api/)?
The reason I ask is that the keys from the API Explorer are set to expire periodically, they're not supposed to be reused.
You need to have [created an app](https://www.flickr.com/services/apps/create/) and used the ones from there.

**Comment by jgsuess** [comment]
I have created an app as per description. It shows 0 authenticated users.
Does that mean I have to run auth first? Where do I find the API Explorer
key test key? I will try the example call with that. If that works, the
issue will be with my authentication.

**Comment by boncey** [comment]
Hmm, it seems I was mistaken, you can get an API key from the API Explorer but not a secret.

Anyway, you shouldn't need to go through any auth process just to call the `flickr.test.echo` method but if you want to give auth a try [there's an example here](https://github.com/boncey/Flickr4Java/blob/master/Flickr4Java/src/examples/java/AuthExample.java).

**Comment by TKouchoanou** [comment]
I have got the same error com.flickr4java.flickr.FlickrException: 100: Invalid API Key (Key has invalid format)

I am using spring boot 

=> this is how i create Flickr bean  

  @Bean
    public Flickr flickr() throws FlickrException {
        Flickr f = new Flickr(apiKey, apiSecret, new REST());
        Auth auth = new Auth();
        auth.setToken(appKey);
        auth.setTokenSecret(appSecret);
        auth.setPermission(Permission.DELETE);
        RequestContext.getRequestContext().setAuth(auth);
        return f;
    }

=> this is how i call the api 

 public  String savePhoto(InputStream photo,String title) throws FlickrException {
        UploadMetaData uploadMetaData= new UploadMetaData();
        uploadMetaData.setTitle(title);
        String photoId=flickr.getUploader().upload(photo,uploadMetaData);
        return flickr.getPhotosInterface().getPhoto(photoId).getMedium640Url();
    }

=> i have generate appKey et appSecret like this 

 Flickr f = new Flickr(apiKey, apiSecret, new REST());
        OAuth10aService aService= new ServiceBuilder(apiKey)
                .apiSecret(apiSecret)
                .build(FlickrApi.instance(FlickrApi.FlickrPerm.DELETE));
        final Scanner scanner= new Scanner(System.in);
        final OAuth1RequestToken requestToken= aService.getRequestToken();
        final String OauthUrl= aService.getAuthorizationUrl(requestToken);

        System.out.println(OauthUrl);
        System.out.println("Paste it here >>");

        final  String authVerifier= scanner.nextLine();
        OAuth1AccessToken accessToken =aService.getAccessToken(requestToken,authVerifier);

        System.out.println("-------------------ACCESS TOKEN-------------------");

        System.out.println(accessToken.getToken());
        System.out.println(accessToken.getTokenSecret());

        Auth auth = f.getAuthInterface().checkToken(accessToken);

        System.out.println("-------------------AUTH-------------------");
        System.out.println(auth.getToken());
        System.out.println(auth.getTokenSecret());

**Comment by boncey** [comment]
Hi @TKouchoanou , your code looks legit.
Have you tried the [AuthExample](https://github.com/boncey/Flickr4Java/blob/master/src/examples/java/AuthExample.java) code?

**Comment by labibbenali** [comment]
Hi @TKouchoanou , i use the same code as you , and i have the same error , did you fix it please??

**Comment by labibbenali** [comment]
Hi @boncey i have the same probleme as @TKouchoanou i have exactly the same code , even i tried the AuthExemple code it give me the same appkey and secretKey that i have !!

**Comment by boncey** [comment]
Hello @labibbenali, I'm on holiday now until August. Will take a look when I get back.

**Comment by labibbenali** [comment]
ok ,thank you

**Comment by boncey** [comment]
@TKouchoanou and @labibbenali I've just tried the AuthExample and the code that was posted above and they worked fine.
I authorised my account and uploaded a photo without any errors.

Are you sure your API keys and Auth tokens are all correct?
I will need more info to try to help as the library seems to be working correctly.

**Comment by labibbenali** [comment]
hey @boncey , thnks for your answer , i fixed the problem. instead create a function auth with @Bean , i just put the content of this function in the function that call the api and now it work

**Comment by Nabil15Daghbari** [comment]
@labibbenali 
I Hope You 're all right 
I have the exact same code  as @TKouchoanou  , I have the same problem, but I cant solve It;
please help me .

**Comment by Nabil15Daghbari** [comment]
@labibbenali 
please send me your code on my address 
nabil.daghbari5@gmail.com

**Comment by labibbenali** [comment]
i just combine the two function

public class FlickrServiceImpl implements FlickrService {
    @Value("${flickr.apiKey}")
    private String apiKey;

    @Value("${flickr.apiSecret}")
    private String apiSecret;

    @Value("${flickr.appKey}")
    private String appKey;

    @Value("${flickr.appSecret}")
    private String appSecret;


    @Override
    public String savePhoto(InputStream photo, String title) throws FlickrException {
        Flickr flickr = new Flickr(apiKey, apiSecret, new REST());
        Auth auth = new Auth();
        auth.setPermission(Permission.DELETE);
        auth.setToken(appKey);
        auth.setTokenSecret(appSecret);

        RequestContext requestContext = RequestContext.getRequestContext();
        requestContext.setAuth(auth);
        flickr.setAuth(auth);

        UploadMetaData uploadMetaData = new UploadMetaData();
        uploadMetaData.setTitle(title);
        String photoId = flickr.getUploader().upload(photo, uploadMetaData);
        return flickr.getPhotosInterface().getPhoto(photoId).getMedium640Url();
    }

}

**Comment by roufaouissantos** [comment]
> je viens de combiner les deux fonctions
> 
> classe publique FlickrServiceImpl implémente FlickrService { @value("${flickr.apiKey}") chaîne privée apiKey ;
> 
> ```
> @Value("${flickr.apiSecret}")
> private String apiSecret;
> 
> @Value("${flickr.appKey}")
> private String appKey;
> 
> @Value("${flickr.appSecret}")
> private String appSecret;
> 
> 
> @Override
> public String savePhoto(InputStream photo, String title) throws FlickrException {
>     Flickr flickr = new Flickr(apiKey, apiSecret, new REST());
>     Auth auth = new Auth();
>     auth.setPermission(Permission.DELETE);
>     auth.setToken(appKey);
>     auth.setTokenSecret(appSecret);
> 
>     RequestContext requestContext = RequestContext.getRequestContext();
>     requestContext.setAuth(auth);
>     flickr.setAuth(auth);
> 
>     UploadMetaData uploadMetaData = new UploadMetaData();
>     uploadMetaData.setTitle(title);
>     String photoId = flickr.getUploader().upload(photo, uploadMetaData);
>     return flickr.getPhotosInterface().getPhoto(photoId).getMedium640Url();
> }
> ```
> 
> }

Bonjour svp jai eu le meme probleme comment vous avec pu configurer flickr api avec spring boot j'utilise STS
